### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by chabir** [ChargedMonk/Social-Distancing-using-YOLOv5#1]
Observation: your repo is under scrutiny on a worldwide forum (Kaggle). You can't change a GPLv3 licence (original yolov5) into MIT licence: you need to keep the GPL licence...

**Comment by ChargedMonk** [comment]
@chabir I thought adding the link to the original repository was sufficient which was a mistake on my part. I will be updating it today. Thanks for informing.

**Comment by chabir** [comment]
You are welcomed. I didn't anything about licensing either on Github until 10 days ago...
